### ISSUE TITLE
how to use this plugin via cloudify-manager?

### ISSUE THREAD

**Issue by modoojunko** [cloudify-cosmo/cloudify-ansible-plugin#5]
I noticed this plugin.

It needs playbook and inventory of playbook, of cause ssh-key is needed, also hosts, but the vars file for the playbook is out of this plugin?

That means I need to maintain my playbook via ansible way not in cloudify-manager when there only has one parameter has changed in vars file ? Example: apache was installled in /usr/local/apache, I need to install it to another path like /var/apache. How to do this via this plugin?

**Comment by EarthmanT** [comment]
As the plugin is now, it's really the simplest implementation. Variables would probably need to be defined in the playbook.

I think using something like is covered here, you may be able to manage those variables, and perhaps also change the install path:

http://docs.ansible.com/playbooks_variables.html#variables-defined-in-a-playbook
http://docs.ansible.com/playbooks_variables.html#using-variables-about-jinja2

**Comment by EarthmanT** [comment]
As the plugin is now, it's really the simplest implementation. Variables would probably need to be defined in the playbook.

I think using something like is covered here, you may be able to manage those variables, and perhaps also change the install path:

http://docs.ansible.com/playbooks_variables.html#variables-defined-in-a-playbook
http://docs.ansible.com/playbooks_variables.html#using-variables-about-jinja2

**Comment by modoojunko** [comment]
"See the working example for more detail." I noticed this too.

where is the runnin example?

and how do I replace these parameters?

{
  "image": "Ubuntu Server 12.04.5 LTS (amd64 20140927) - Partner Image",
  "flavor": "standard.small", 
  "key_name": "agent_key.pem",
  "playbook_file": "playbook.yaml"
}

what are they mean? example:"playbook_file": "playbook.yaml" it means the path ?or the file name?

**Comment by EarthmanT** [comment]
The working example is this: https://github.com/EarthmanT/cloudify-ansible-plugin/tree/master/ansible_plugin/tests/blueprints

"playbook.yaml" should be in the same directory as "blueprint.yaml".

The path is the blueprints directory, which is the path from "-p" when you run:
    cfy blueprints upload -p ./some/directory/and/blueprint.yaml

**Comment by modoojunko** [comment]
hi，did you tried "simple" model ? I noticed your test blueprint only has cloudify.openstack model.

**Comment by EarthmanT** [comment]
Hi, No, I have not tried a “simple” model.
